name: MyModels APK

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant gradlew permission
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Get versionName
        run: |
          VERSION=$(grep versionName app/build.gradle | head -1 | awk -F '"' '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create release folder
        run: mkdir -p release

      - name: Copy APK
        run: |
          cp app/build/outputs/apk/debug/app-debug.apk release/Mymodels-${VERSION}.apk

      - name: Generate changelog
        run: |
          git log -5 --pretty=format:"- %s" > release/CHANGELOG.txt

      - name: Create Git tag
        run: |
          git tag v${VERSION} || echo "Tag already exists"
          git push origin v${VERSION} || echo "Tag already pushed"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: MyModels v${{ env.VERSION }}
          body_path: release/CHANGELOG.txt
          files: release/Mymodels-${{ env.VERSION }}.apk